#!/bin/sh

# 设置基本环境变量
export LC_ALL=C
export ALLOW_MISSING_DEPENDENCIES=true

# 橙狐编译设置
export FOX_VANILLA_BUILD=1
export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
export TARGET_DEVICE_ALT=corvette

# 二进制文件设置
export FOX_REPLACE_BUSYBOX_PS=1
export FOX_USE_BASH_SHELL=1
export FOX_ASH_IS_BASH=1
export FOX_REPLACE_TOOLBOX_GETPROP=1
export FOX_USE_TAR_BINARY=1
export FOX_USE_XZ_UTILS=1
